# 파일 읽어올 때 주피터랑 같은 폴더에 넣어놓기
- sas 파일 읽어올 때 : df_og = pd.read_sas('데이터명.sas7bdat)
- csv 파일 읽어올 때 : df_og = pd.read_csv('데이터명.csv')
- 엑셀 파일 읽어올 때 : df_og = pd.read_excel("qe_data.xlsx", header = 1)

# 분석용 데이터셋 복사
df = df_og.copy()

In [ ]:
import pandas as pd 
import numpy as np
df16 = pd.read_sas('/content/drive/MyDrive/쌉고급데이터마이닝/국건영 원본 데이터셋/hn16_all.sas7bdat')
df16

               mod_d             ID       ID_fam  ...   HEI_CHO   HEI_FAT    HEI_EN
0     b'2020.09.01.'  b'A651172801'  b'A6511728'  ...  5.000000  5.000000  5.000000
1     b'2020.09.01.'  b'A651172802'  b'A6511728'  ...  4.556620  5.000000  0.000000
2     b'2020.09.01.'  b'A651183001'  b'A6511830'  ...  5.000000  5.000000  4.149154
3     b'2020.09.01.'  b'A651183002'  b'A6511830'  ...       NaN       NaN       NaN
4     b'2020.09.01.'  b'A651183003'  b'A6511830'  ...       NaN       NaN       NaN
...              ...            ...          ...  ...       ...       ...       ...
8145  b'2020.09.01.'  b'R654353001'  b'R6543530'  ...  4.410503  5.000000  5.000000
8146  b'2020.09.01.'  b'R654353002'  b'R6543530'  ...  5.000000  5.000000  5.000000
8147  b'2020.09.01.'  b'R654370001'  b'R6543700'  ...  3.120407  4.907240  0.941910
8148  b'2020.09.01.'  b'R654370002'  b'R6543700'  ...  1.282761  0.145117  2.385985
8149  b'2020.09.01.'  b'R654370003'  b'R6543700'  ...  3.909199  5.000000  5.000000

[8150 rows x 799 columns]

In [ ]:
df17 = pd.read_sas('/content/drive/MyDrive/쌉고급데이터마이닝/국건영 원본 데이터셋/hn17_all.sas7bdat')
df17

               mod_d             ID       ID_fam  ...   HEI_CHO   HEI_FAT    HEI_EN
0     b'2020.09.01.'  b'A601169401'  b'A6011694'  ...  0.000000  1.125768  5.000000
1     b'2020.09.01.'  b'A601169402'  b'A6011694'  ...  4.175511  5.000000  3.885867
2     b'2020.09.01.'  b'A601177901'  b'A6011779'  ...  5.000000  5.000000  5.000000
3     b'2020.09.01.'  b'A601177902'  b'A6011779'  ...  5.000000  5.000000  4.231573
4     b'2020.09.01.'  b'A601177903'  b'A6011779'  ...       NaN       NaN       NaN
...              ...            ...          ...  ...       ...       ...       ...
8122  b'2020.09.01.'  b'R604313902'  b'R6043139'  ...  5.000000  5.000000  2.745224
8123  b'2020.09.01.'  b'R604313904'  b'R6043139'  ...  0.000000  0.000000  0.000000
8124  b'2020.09.01.'  b'R604313905'  b'R6043139'  ...       NaN       NaN       NaN
8125  b'2020.09.01.'  b'R604346201'  b'R6043462'  ...  5.000000  5.000000  5.000000
8126  b'2020.09.01.'  b'R604346202'  b'R6043462'  ...  5.000000  5.000000  2.668032

[8127 rows x 857 columns]

In [ ]:
df18 = pd.read_sas('/content/drive/MyDrive/쌉고급데이터마이닝/국건영 원본 데이터셋/hn18_all.sas7bdat')
df18

               mod_d             ID       ID_fam  ...   HEI_CHO   HEI_FAT    HEI_EN
0     b'2020.09.01.'  b'A901020501'  b'A9010205'  ...  5.000000  5.000000  0.000000
1     b'2020.09.01.'  b'A901021301'  b'A9010213'  ...  4.345249  2.956568  5.000000
2     b'2020.09.01.'  b'A901021302'  b'A9010213'  ...  5.000000  5.000000  5.000000
3     b'2020.09.01.'  b'A901022601'  b'A9010226'  ...       NaN       NaN       NaN
4     b'2020.09.01.'  b'A901023303'  b'A9010233'  ...  0.000000  0.000000  1.244134
...              ...            ...          ...  ...       ...       ...       ...
7987  b'2020.09.01.'  b'R904028902'  b'R9040289'  ...  2.797653  5.000000  0.000000
7988  b'2020.09.01.'  b'R904029201'  b'R9040292'  ...  0.000000  0.000000  0.000000
7989  b'2020.09.01.'  b'R904029202'  b'R9040292'  ...  0.000000  0.000000  1.288707
7990  b'2020.09.01.'  b'R904029203'  b'R9040292'  ...       NaN       NaN       NaN
7991  b'2020.09.01.'  b'R904029204'  b'R9040292'  ...       NaN       NaN       NaN

[7992 rows x 785 columns]

In [ ]:
df_all = pd.concat([df16,df17,df18])

In [ ]:
df_att = df_all[["sex","age","D_1_1","Total_slp_wk","BP1","BO1","BE5_1","BE8_1","BE8_2","BP5","HE_ht","HE_wt"]]

In [ ]:
df_att.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24269 entries, 0 to 7991
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sex           24269 non-null  float64
 1   age           24269 non-null  float64
 2   D_1_1         23136 non-null  float64
 3   Total_slp_wk  21926 non-null  float64
 4   BP1           23136 non-null  float64
 5   BO1           23136 non-null  float64
 6   BE5_1         23136 non-null  float64
 7   BE8_1         23136 non-null  float64
 8   BE8_2         23136 non-null  float64
 9   BP5           23136 non-null  float64
 10  HE_ht         23065 non-null  float64
 11  HE_wt         23125 non-null  float64
dtypes: float64(12)
memory usage: 2.4 MB

In [ ]:
# BMI [BMI] (명목) 변수 생성
df_att['BMI'] = (df_att['HE_wt'] / (df_att['HE_ht'] / 100)**2)
df_att.loc[df_att['BMI'] < 25, 'BMI'] = 0
df_att.loc[df_att['BMI'] >= 25, 'BMI'] = 1
print(df_att['BMI'].value_counts())
print("==========================")
print(df_att['BMI'])

0.0    16298
1.0     6765
Name: BMI, dtype: int64
==========================
0       0.0
1       0.0
2       0.0
3       1.0
4       0.0
       ...
7987    0.0
7988    1.0
7989    0.0
7990    0.0
7991    0.0
Name: BMI, Length: 24269, dtype: float64

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
df_csn = df_att.loc[(df_att['age']>=12) & (df_att['age']<=18), :]  # 청소년 (만12세~18세) 데이터 생성
df_csn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1681 entries, 16 to 7973
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sex           1681 non-null   float64
 1   age           1681 non-null   float64
 2   D_1_1         1549 non-null   float64
 3   Total_slp_wk  1548 non-null   float64
 4   BP1           1549 non-null   float64
 5   BO1           1549 non-null   float64
 6   BE5_1         1549 non-null   float64
 7   BE8_1         1549 non-null   float64
 8   BE8_2         1549 non-null   float64
 9   BP5           1549 non-null   float64
 10  HE_ht         1551 non-null   float64
 11  HE_wt         1552 non-null   float64
 12  BMI           1551 non-null   float64
dtypes: float64(13)
memory usage: 183.9 KB

In [ ]:
# 하루 평균 앉아서 보내는 시간(분 단위) 변수 생성
df_csn["SitTime"] = df_csn["BE8_1"]*60 + df_csn['BE8_2']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_cgh = pd.read_csv('/content/drive/MyDrive/쌉고급데이터마이닝/라스트/cgh18.csv')
a= df_cgh.iloc[:,1:]
a

       sex   age  D_1_1  BP1  BO1  BE5_1  BP5  BMI  Total_slp_wk      SitTime
0      1.0  13.0    3.0  4.0  1.0    1.0  1.0  0.0         440.0   531.428571
1      1.0  13.0    1.0  4.0  3.0    1.0  2.0  0.0         510.0   385.714286
2      1.0  12.0    1.0  3.0  3.0    2.0  2.0  0.0         450.0   960.571429
3      1.0  12.0    2.0  3.0  3.0    3.0  2.0  0.0           NaN   411.428571
4      1.0  12.0    2.0  2.0  5.0    1.0  2.0  1.0         500.0    67.142857
...    ...   ...    ...  ...  ...    ...  ...  ...           ...          ...
57968  2.0  18.0    2.0  3.0  3.0    1.0  2.0  0.0         480.0   437.142857
57969  2.0  17.0    1.0  2.0  4.0    2.0  1.0  1.0         360.0   814.285714
57970  2.0  17.0    4.0  1.0  3.0    2.0  1.0  0.0         420.0  1080.000000
57971  2.0  17.0    3.0  4.0  5.0    2.0  1.0  0.0         660.0   514.285714
57972  2.0  17.0    4.0  1.0  2.0    1.0  1.0  0.0         330.0   780.000000

[57973 rows x 10 columns]

In [ ]:
df_att = pd.concat([df_csn,a])

In [ ]:
df_att['BMI'] = df_att['BMI'].astype('category')

In [ ]:
df_att.loc[(df_att['BE8_1'] == 88) |(df_att['BE8_1'] == 99) , 'BE8_1'] = np.nan 
df_att.loc[(df_att['BE8_2'] == 88) |(df_att['BE8_2'] == 99) , 'BE8_2'] = np.nan

In [ ]:
print(df_att['BE8_1'].value_counts())
print("="*14)
print(df_att['BE8_2'].value_counts())

10.0    361
12.0    264
8.0     147
9.0     127
13.0    127
15.0    110
11.0    109
14.0     99
7.0      64
16.0     51
6.0      31
5.0      16
17.0     14
18.0     10
3.0       4
1.0       2
4.0       2
2.0       1
19.0      1
Name: BE8_1, dtype: int64
==============
0.0     1446
30.0      71
40.0       7
20.0       6
10.0       4
50.0       2
35.0       1
15.0       1
55.0       1
25.0       1
Name: BE8_2, dtype: int64

# 필요 Attribute만 가져오기

In [ ]:
df_att = df_att.loc[:,['sex','age','D_1_1','BP1','BO1','BE5_1','BP5','BMI','Total_slp_wk','SitTime']]

In [ ]:
# 1주일간 근력운동 일수 (등간)
print(df_att['BE5_1'].value_counts()) # 8 비해당 929명, 9 모름, 무응답 : 267명 -> NA
df_att.loc[(df_att['BE5_1'] == 8) |(df_att['BE5_1'] == 9) , 'BE5_1'] = np.nan  #na 값 처리
print(df_att['BE5_1'].value_counts())
#df_att['BE5_1'].astype('int64') # na 제거하거나 대체하면 에러 안남.

1.0    29034
2.0    10118
3.0     6849
6.0     6214
4.0     4913
5.0     2389
9.0        5
Name: BE5_1, dtype: int64
1.0    29034
2.0    10118
3.0     6849
6.0     6214
4.0     4913
5.0     2389
Name: BE5_1, dtype: int64

In [ ]:
# 주관적 건강상태 [D_1_1]] (순서)
from pandas.api.types import CategoricalDtype
print(df_att['D_1_1'].value_counts())
print("==========================")
df_att.loc[df_att['D_1_1'] == 9, 'D_1_1'] = np.nan
df_att['D_1_1'] = df_att['D_1_1'].astype(CategoricalDtype(ordered=True))
print(df_att['D_1_1'].value_counts())
print("==========================")
print(df_att['D_1_1'])

2.0    26475
1.0    15884
3.0    13210
4.0     3688
5.0      262
9.0        3
Name: D_1_1, dtype: int64
==========================
2.0    26475
1.0    15884
3.0    13210
4.0     3688
5.0      262
Name: D_1_1, dtype: int64
==========================
16       3.0
20       2.0
21       2.0
34       3.0
40       2.0
        ...
57968    2.0
57969    1.0
57970    4.0
57971    3.0
57972    4.0
Name: D_1_1, Length: 59654, dtype: category
Categories (5, float64): [1.0 < 2.0 < 3.0 < 4.0 < 5.0]

In [ ]:
# 2주 이상 연속 우울감 여부 [BP5] (명목)
print(df_att['BP5'].value_counts())
print("==========================")
df_att.loc[df_att['BP5'] == 8, 'BP5'] = np.nan
df_att.loc[df_att['BP5'] == 9, 'BP5'] = np.nan
df_att['BP5'] = df_att['BP5'].astype('category')
print(df_att['BP5'].value_counts())
print("==========================")
print(df_att['BP5'])

2.0    43328
1.0    16192
9.0        2
Name: BP5, dtype: int64
==========================
2.0    43328
1.0    16192
Name: BP5, dtype: int64
==========================
16       2.0
20       2.0
21       2.0
34       1.0
40       2.0
        ...
57968    2.0
57969    1.0
57970    1.0
57971    1.0
57972    1.0
Name: BP5, Length: 59654, dtype: category
Categories (2, float64): [1.0, 2.0]

In [ ]:
# 평소 스트레스 인지정도 [BP1] (순서)
from pandas.api.types import CategoricalDtype
print(df_att['BP1'].value_counts())
print("==========================")
df_att.loc[df_att['BP1'] == 8, 'BP1'] = np.nan
df_att.loc[df_att['BP1'] == 9, 'BP1'] = np.nan

df_att['BP1'] = df_att['BP1'].astype(CategoricalDtype(ordered=True))
print(df_att['BP1'].value_counts())
print("==========================")
print(df_att['BP1'])

3.0    25511
2.0    17775
4.0     9264
1.0     6970
9.0        2
Name: BP1, dtype: int64
==========================
3.0    25511
2.0    17775
4.0     9264
1.0     6970
Name: BP1, dtype: int64
==========================
16       4.0
20       3.0
21       3.0
34       3.0
40       3.0
        ...
57968    3.0
57969    2.0
57970    1.0
57971    4.0
57972    1.0
Name: BP1, Length: 59654, dtype: category
Categories (4, float64): [1.0 < 2.0 < 3.0 < 4.0]

In [ ]:
# 주관적 체형 인지 [BO1] (순서)
from pandas.api.types import CategoricalDtype
print(df_att['BO1'].value_counts())
print("==========================")
df_att.loc[df_att['BO1'] == 8, 'BO1'] = np.nan
df_att.loc[df_att['BO1'] == 9, 'BO1'] = np.nan

df_att['BO1'] = df_att['BO1'].astype(CategoricalDtype(ordered=True))
print(df_att['BO1'].value_counts())
print("==========================")
print(df_att['BO1'])

3.0    21618
4.0    19138
2.0    12310
5.0     3945
1.0     2509
9.0        2
Name: BO1, dtype: int64
==========================
3.0    21618
4.0    19138
2.0    12310
5.0     3945
1.0     2509
Name: BO1, dtype: int64
==========================
16       5.0
20       3.0
21       4.0
34       4.0
40       2.0
        ...
57968    3.0
57969    4.0
57970    3.0
57971    5.0
57972    2.0
Name: BO1, Length: 59654, dtype: category
Categories (5, float64): [1.0 < 2.0 < 3.0 < 4.0 < 5.0]

In [ ]:
# 1주일간 근력운동 일수 [BE5_1]] (순서)
from pandas.api.types import CategoricalDtype
print(df_att['BE5_1'].value_counts())
print("==========================")
df_att['BE5_1'] = df_att['BE5_1'].astype(CategoricalDtype(ordered=True))
print(df_att['BE5_1'].value_counts())
print("==========================")
print(df_att['BE5_1'])

1.0    29034
2.0    10118
3.0     6849
6.0     6214
4.0     4913
5.0     2389
Name: BE5_1, dtype: int64
==========================
1.0    29034
2.0    10118
3.0     6849
6.0     6214
4.0     4913
5.0     2389
Name: BE5_1, dtype: int64
==========================
16       1.0
20       1.0
21       1.0
34       1.0
40       1.0
        ...
57968    1.0
57969    2.0
57970    2.0
57971    2.0
57972    1.0
Name: BE5_1, Length: 59654, dtype: category
Categories (6, float64): [1.0 < 2.0 < 3.0 < 4.0 < 5.0 < 6.0]

In [ ]:
df_att['sex'] = df_att['sex'].astype('category')

In [ ]:
df_att.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59654 entries, 16 to 57972
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sex           59654 non-null  category
 1   age           59390 non-null  float64
 2   D_1_1         59519 non-null  category
 3   BP1           59520 non-null  category
 4   BO1           59520 non-null  category
 5   BE5_1         59517 non-null  category
 6   BP5           59520 non-null  category
 7   BMI           57927 non-null  category
 8   Total_slp_wk  52749 non-null  float64
 9   SitTime       56245 non-null  float64
dtypes: category(7), float64(3)
memory usage: 2.2 MB

# 결측치 처리
### 전체: df_all
### 남자: df_all_b
### 여자: df_all_g

In [ ]:
# 결측치 제거
df_new = df_att.dropna(axis=0)
df_new = df_new.reset_index()
df_all = df_new.copy()

In [ ]:
#남자 먹이기
df_all_b = df_all.loc[df_all["sex"]==1,:]
df_all_b = df_all_b.drop('sex', axis = 1)

df_all_b.shape

(23871, 10)

In [ ]:
#DU자 먹이기
df_all_g = df_all.loc[df_all["sex"]==2,:]
df_all_g = df_all_g.drop('sex', axis = 1)

df_all_g.shape

(24835, 10)

In [ ]:
df_all = df_all.iloc[:,1:11]
df_all_g = df_all_g.iloc[:,1:11]
df_all_b = df_all_b.iloc[:,1:11]

df_all.shape, df_all_b.shape, df_all_g.shape

((48706, 10), (23871, 9), (24835, 9))

# outlier 제거

In [ ]:
def remove_outlier(d_cp, column):
    fraud_column_data = d_cp[column]
    quan_25 = np.percentile(fraud_column_data, 25)
    quan_75 = np.percentile(fraud_column_data, 75)
    
    iqr = quan_75 - quan_25
    iqr = iqr * 1.5
    lowest = quan_25 - iqr
    highest = quan_75 + iqr
    outlier_index = fraud_column_data[(fraud_column_data<lowest) | (fraud_column_data > highest)].index
    d_cp.drop(outlier_index, axis=0, inplace=True)
    return d_cp

In [ ]:
print(df_all.shape)
df_all = remove_outlier(df_all, 'SitTime')
df_all = remove_outlier(df_all, 'Total_slp_wk')
print(df_all.shape)

(48706, 10)
(48684, 10)

In [ ]:
print(df_all_g.shape)
df_all_g = remove_outlier(df_all_g, 'SitTime')
df_all_g = remove_outlier(df_all_g, 'Total_slp_wk')
print(df_all_g.shape)

(24835, 9)
(24775, 9)

In [ ]:
print(df_all_b.shape)
df_all_b = remove_outlier(df_all_b, 'SitTime')
df_all_b = remove_outlier(df_all_b, 'Total_slp_wk')
print(df_all_b.shape)

(23871, 9)
(23839, 9)

# Train_test 나누기와 업샘플링 그리고 scaling

In [ ]:
def train_test_split_and_upsample(df_input, scaling):
    
    df = df_input.copy()
    
    df = df.astype('category')
    df['SitTime'] = df['SitTime'].astype('float64')
    df['Total_slp_wk'] = df['Total_slp_wk'].astype('float64')
    
    df_class_0 = df[df['BMI'] == 0]
    df_class_1 = df[df['BMI'] == 1]
    
    df_class_1_over = df_class_1.sample(df_class_0.shape[0], replace=True, random_state=10)
    df_over = pd.concat([df_class_0, df_class_1_over], axis=0)
    
    feature_columns = list(df.columns.difference(['BMI']))
    X = df[feature_columns]
    y = df[['BMI']]
    
    X_res = df_over[feature_columns]
    y_res = df_over[['BMI']]
    
    from sklearn.model_selection import train_test_split
    from sklearn import preprocessing
    train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.3, random_state = 0, stratify = y) 
    train_x_res, test_x_res, train_y_res, test_y_res = train_test_split(X_res, y_res, test_size = 0.3, random_state = 0, stratify = y_res)
    
    train_x = train_x.reset_index().iloc[:,1:]
    tmp2 = train_x.loc[:,['Total_slp_wk', 'SitTime']]
    train_x = train_x.drop(['Total_slp_wk', 'SitTime'], axis=1)
    train_x = pd.concat([train_x, tmp2], axis=1)

    test_x = test_x.reset_index().iloc[:,1:]
    tmp2 = test_x.loc[:,['Total_slp_wk', 'SitTime']]
    test_x = test_x.drop(['Total_slp_wk', 'SitTime'], axis=1)
    test_x = pd.concat([test_x, tmp2], axis=1)

    train_y = train_y.reset_index().iloc[:,1:]
    
    test_y = test_y.reset_index().iloc[:,1:]
    
    train_x_res = train_x_res.reset_index().iloc[:,1:]
    tmp2 = train_x_res.loc[:,['Total_slp_wk', 'SitTime']]
    train_x_res = train_x_res.drop(['Total_slp_wk', 'SitTime'], axis=1)
    train_x_res = pd.concat([train_x_res, tmp2], axis=1)

    train_y_res = train_y_res.reset_index().iloc[:,1:]
    
    # 최소값(Min)과 최대값(Max)을 사용해서 '0~1' 사이의 범위(range)로 데이터를 표준화해주는 '0~1 변환 사용 (MinMaxScaler())
    
    if scaling == True: 
        min_max_scaler = preprocessing.MinMaxScaler()
        temp = min_max_scaler.fit_transform(train_x.loc[:,['Total_slp_wk','SitTime']])
        temp = pd.DataFrame(temp, columns = ['Total_slp_wk','SitTime'])
        train_x = train_x.drop(['Total_slp_wk', 'SitTime'], axis=1)
        train_x = pd.concat([train_x, temp], axis=1)

        min_max_scaler = preprocessing.MinMaxScaler()
        temp = min_max_scaler.fit_transform(test_x.loc[:,['Total_slp_wk','SitTime']])
        temp = pd.DataFrame(temp, columns = ['Total_slp_wk','SitTime'])
        test_x = test_x.drop(['Total_slp_wk', 'SitTime'], axis=1)
        test_x = pd.concat([test_x, temp], axis=1)

        min_max_scaler = preprocessing.MinMaxScaler()
        temp = min_max_scaler.fit_transform(train_x_res.loc[:,['Total_slp_wk','SitTime']])
        temp = pd.DataFrame(temp, columns = ['Total_slp_wk','SitTime'])
        train_x_res = train_x_res.drop(['Total_slp_wk', 'SitTime'], axis=1)
        train_x_res = pd.concat([train_x_res, temp], axis=1)    

    
    


    #train = pd.concat([train_x, train_y], axis=1)
    #train_res = pd.concat([train_x_res, train_y_res], axis=1)
    
    return train_x, test_x, train_y, test_y, train_x_res, train_y_res

In [ ]:
df_all.to_csv("df_all.csv")
df_all_b.to_csv("df_all_b.csv")
df_all_g.to_csv("df_all_g.csv")

In [ ]:
#df_all 대신 df_all_b, df_all_g를 넣으면 걔네들에 대해서 트레인, 테스트, 오버샘플링 출력

tmp = train_test_split_and_upsample(df_all, scaling=True) 
train_x = tmp[0]
train_y = tmp[2]
test_x = tmp[1]
test_y = tmp[3]
train_x_res = tmp[4]
train_y_res = tmp[5]

In [ ]:
train_x_res

      BE5_1  BO1  BP1  BP5 D_1_1   age  sex  Total_slp_wk   SitTime
0       2.0  4.0  3.0  2.0   1.0  18.0  1.0      0.517857  0.347826
1       1.0  3.0  3.0  1.0   3.0  17.0  2.0      0.375000  0.242236
2       6.0  3.0  2.0  1.0   2.0  16.0  1.0      0.464286  0.130435
3       6.0  4.0  3.0  2.0   2.0  18.0  1.0      0.357143  0.074534
4       4.0  4.0  4.0  2.0   1.0  15.0  1.0      0.857143  0.479814
...     ...  ...  ...  ...   ...   ...  ...           ...       ...
58267   3.0  4.0  2.0  2.0   3.0  17.0  2.0      0.446429  0.658385
58268   2.0  5.0  3.0  1.0   2.0  14.0  2.0      0.571429  0.322981
58269   1.0  3.0  3.0  1.0   1.0  15.0  2.0      0.750000  0.298137
58270   2.0  5.0  1.0  2.0   3.0  16.0  2.0      0.446429  0.447205
58271   2.0  4.0  3.0  2.0   2.0  13.0  1.0      0.625000  0.099379

[58272 rows x 9 columns]